---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    project: person-app
    version: 1.0-SNAPSHOT
    group: gh.atsticks.demos.ee2ms
  name: person-app
spec:
  replicas: 1
  selector:
    project: person-app
    version: 1.0-SNAPSHOT
    group: gh.atsticks.demos.ee2ms
  template:
    metadata:
      labels:
        project: person-app
        version: 1.0-SNAPSHOT
        group: gh.atsticks.demos.ee2ms
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: default/person-app:latest
        imagePullPolicy: IfNotPresent
        name: person-app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        securityContext:
          privileged: false
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MYSQL_ROOT_PASSWORD
          value: secret01
        - name: MYSQL_USER
          value: personapp
        - name: MYSQL_PASSWORD
          value: pwd334
        - name: MYSQL_DATABASE
          value: person
        image: centos/mariadb-101-centos7:latest
        imagePullPolicy: IfNotPresent
        name: person-db
        ports:
        - containerPort: 3306
          name: http
          protocol: TCP
        securityContext:
          privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - person-app
        from:
          kind: ImageStreamTag
          name: person-app:latest
      type: ImageChange
