metadata:
  annotations:
    configmap.fabric8.io/update-on-change: ${project.artifactId}
spec:
  replicas: 1
  template:
    spec:
      metadata:
        labels:
          application:  "person"
          tier:         "data"
          component:    "person-all"