FROM centos/mariadb-101-centos7:latest

MAINTAINER atsticks@gmail.com
LABEL version=latest
LABEL artifactId=gh.atsticks.demos.ee2ms/person-db:1.0

EXPOSE 3306
ENV MYSQL_ROOT_PASSWORD=secret01
ENV MYSQL_USER=personapp
ENV MYSQL_PASSWORD=pwd334
ENV MYSQL_DATABASE=person

